version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'ubook_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'wh-eJ89*8N'
      MYSQL_ROOT_PASSWORD: 'mysql'
  web:
    build: .
    volumes:
      - .:/root
    ports:
      - "8600:8600"
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOST_TIMEOUT: 5
      MYSQL_DATABASE: 'ubook_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'wh-eJ89*8N'
      MYSQL_ROOT_PASSWORD: 'mysql'
    restart: on-failure
    depends_on:
      - db