# Generated by Django 3.0.4 on 2020-04-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
    ]
