# Generated by Django 3.0.3 on 2020-04-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_friend_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
