# Generated by Django 3.0.4 on 2020-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
