# Generated by Django 3.0.3 on 2020-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_friend'),
        ('user_profile', '0004_auto_20200505_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, to='blog.Post'),
        ),
    ]
