# Generated by Django 3.0.3 on 2020-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200429_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
